'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Gallery

  Partial Public Class AlbumEdit

    '''<summary>
    '''trNavigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trNavigation As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''celHeaderLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celHeaderLeft As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''celGalleryMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celGalleryMenu As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''celBreadcrumbs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celBreadcrumbs As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''celHeaderRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celHeaderRight As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lblInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rowDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowDetails As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''plName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plName As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAlbumName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlbumName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rqdFieldValidatorTxtName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqdFieldValidatorTxtName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''validateCharacters4txtName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validateCharacters4txtName As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''plTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plTitle As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rqdFieldValidatorTxtTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqdFieldValidatorTxtTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''plAuthor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plAuthor As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtAuthor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAuthor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''plClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plClient As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClient As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''plLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plLocation As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''plDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plDescription As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rowApprovedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowApprovedDate As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''plApprovedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plApprovedDate As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtApprovedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApprovedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdApprovedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdApprovedDate As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''valApprovedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valApprovedDate As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''rowOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowOwner As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''plOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plOwner As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ctlOwnerLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlOwnerLookup As Global.DotNetNuke.Modules.Gallery.WebControls.LookupControl

    '''<summary>
    '''plCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plCategories As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''lstCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstCategories As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''rowUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowUpload As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''galControlUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents galControlUpload As Global.DotNetNuke.Modules.Gallery.WebControls.Upload

    '''<summary>
    '''cmdUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cmdCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rowAlbumGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowAlbumGrid As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ControlAlbum1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ControlAlbum1 As Global.DotNetNuke.Modules.Gallery.WebControls.Album

    '''<summary>
    '''rowRefuse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowRefuse As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''plRefuseTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plRefuseTitle As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''lblRefuse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRefuse As Global.System.Web.UI.WebControls.Label
  End Class
End Namespace
