'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Gallery

  Partial Public Class Container

    '''<summary>
    '''tbContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbContent As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''rowFolders1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowFolders1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''celHeaderLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celHeaderLeft As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''celGalleryMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celGalleryMenu As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''celBreadcrumbs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celBreadcrumbs As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''celHeaderRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celHeaderRight As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowPager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowPager1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''celAltHeaderLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celAltHeaderLeft As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ctlControlPager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlControlPager1 As Global.DotNetNuke.Modules.Gallery.WebControls.Pager

    '''<summary>
    '''lblView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblView As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlGalleryView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGalleryView As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSortBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSortBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlGallerySort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGallerySort As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkDESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDESC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''celAltHeaderRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celAltHeaderRight As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowContent As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''celBodyLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celBodyLeft As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''celContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celContent As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ctlGallery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlGallery As Global.DotNetNuke.Modules.Gallery.Views.GalleryControl

    '''<summary>
    '''celBodyRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celBodyRight As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowPager2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowPager2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''celFooterLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celFooterLeft As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ctlControlPager2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlControlPager2 As Global.DotNetNuke.Modules.Gallery.WebControls.Pager

    '''<summary>
    '''ClearCache control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClearCache As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblStats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStats As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''celFooterRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celFooterRight As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''celleftBottomLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celleftBottomLeft As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''celBottum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celBottum As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''celBottomRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celBottomRight As Global.System.Web.UI.HtmlControls.HtmlTableCell
  End Class
End Namespace
