using DotNetNuke;
using DotNetNuke.Common;
using DotNetNuke.Common.Utilities;
using DotNetNuke.Entities;
using DotNetNuke.Framework;
using DotNetNuke.Security;
using DotNetNuke.Services;
using DotNetNuke.Services.Exceptions;
using DotNetNuke.Services.Localization;
using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Collections.Specialized;
using System.Configuration;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Caching;
using System.Web.SessionState;
using System.Web.Security;
using System.Web.Profile;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------


namespace DotNetNuke.Modules.Gallery
{

	public partial class Container
	{

		///<summary>
		///tbContent control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTable tbContent;
		///<summary>
		///rowFolders1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableRow rowFolders1;
		///<summary>
		///celHeaderLeft control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celHeaderLeft;
		///<summary>
		///celGalleryMenu control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celGalleryMenu;
		///<summary>
		///celBreadcrumbs control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celBreadcrumbs;
		///<summary>
		///celHeaderRight control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celHeaderRight;
		///<summary>
		///rowPager1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableRow rowPager1;
		///<summary>
		///celAltHeaderLeft control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celAltHeaderLeft;
		///<summary>
		///ctlControlPager1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.Modules.Gallery.WebControls.Pager ctlControlPager1;
		///<summary>
		///lblView control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.Label lblView;
		///<summary>
		///ddlGalleryView control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		private global::System.Web.UI.WebControls.DropDownList withEventsField_ddlGalleryView;
		protected global::System.Web.UI.WebControls.DropDownList ddlGalleryView {
			get { return withEventsField_ddlGalleryView; }
			set {
				if (withEventsField_ddlGalleryView != null) {
					withEventsField_ddlGalleryView.SelectedIndexChanged -= ddlGalleryView_SelectedIndexChanged;
				}
				withEventsField_ddlGalleryView = value;
				if (withEventsField_ddlGalleryView != null) {
					withEventsField_ddlGalleryView.SelectedIndexChanged += ddlGalleryView_SelectedIndexChanged;
				}
			}

		}
		///<summary>
		///lblSortBy control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.Label lblSortBy;
		///<summary>
		///ddlGallerySort control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		private global::System.Web.UI.WebControls.DropDownList withEventsField_ddlGallerySort;
		protected global::System.Web.UI.WebControls.DropDownList ddlGallerySort {
			get { return withEventsField_ddlGallerySort; }
			set {
				if (withEventsField_ddlGallerySort != null) {
					withEventsField_ddlGallerySort.SelectedIndexChanged -= ddlGallerySort_SelectedIndexChanged;
				}
				withEventsField_ddlGallerySort = value;
				if (withEventsField_ddlGallerySort != null) {
					withEventsField_ddlGallerySort.SelectedIndexChanged += ddlGallerySort_SelectedIndexChanged;
				}
			}

		}
		///<summary>
		///chkDESC control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		private global::System.Web.UI.WebControls.CheckBox withEventsField_chkDESC;
		protected global::System.Web.UI.WebControls.CheckBox chkDESC {
			get { return withEventsField_chkDESC; }
			set {
				if (withEventsField_chkDESC != null) {
					withEventsField_chkDESC.CheckedChanged -= chkDESC_CheckedChanged;
				}
				withEventsField_chkDESC = value;
				if (withEventsField_chkDESC != null) {
					withEventsField_chkDESC.CheckedChanged += chkDESC_CheckedChanged;
				}
			}

		}
		///<summary>
		///celAltHeaderRight control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celAltHeaderRight;
		///<summary>
		///rowContent control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableRow rowContent;
		///<summary>
		///celBodyLeft control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celBodyLeft;
		///<summary>
		///celContent control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celContent;
		///<summary>
		///ctlGallery control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.Modules.Gallery.Views.GalleryControl ctlGallery;
		///<summary>
		///celBodyRight control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celBodyRight;
		///<summary>
		///rowPager2 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableRow rowPager2;
		///<summary>
		///celFooterLeft control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celFooterLeft;
		///<summary>
		///ctlControlPager2 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.Modules.Gallery.WebControls.Pager ctlControlPager2;
		///<summary>
		///ClearCache control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		private global::System.Web.UI.WebControls.ImageButton withEventsField_ClearCache;
		protected global::System.Web.UI.WebControls.ImageButton ClearCache {
			get { return withEventsField_ClearCache; }
			set {
				if (withEventsField_ClearCache != null) {
					withEventsField_ClearCache.Click -= ClearCache_Click;
				}
				withEventsField_ClearCache = value;
				if (withEventsField_ClearCache != null) {
					withEventsField_ClearCache.Click += ClearCache_Click;
				}
			}

		}
		///<summary>
		///lblStats control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.Label lblStats;
		///<summary>
		///celFooterRight control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celFooterRight;
		///<summary>
		///celleftBottomLeft control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celleftBottomLeft;
		///<summary>
		///celBottum control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celBottum;
		///<summary>
		///celBottomRight control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.HtmlControls.HtmlTableCell celBottomRight;
	}
}
