using DotNetNuke;
using DotNetNuke.Common;
using DotNetNuke.Common.Utilities;
using DotNetNuke.Entities;
using DotNetNuke.Framework;
using DotNetNuke.Security;
using DotNetNuke.Services;
using DotNetNuke.Services.Exceptions;
using DotNetNuke.Services.Localization;
using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Collections.Specialized;
using System.Configuration;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Caching;
using System.Web.SessionState;
using System.Web.Security;
using System.Web.Profile;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------


namespace DotNetNuke.Modules.Gallery
{

	public partial class ExifMetaData
	{

		///<summary>
		///tblViewControl control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTable tblViewControl;
		///<summary>
		///lblTitle control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.Label lblTitle;
		///<summary>
		///ctlExif control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.Modules.Gallery.WebControls.Exif ctlExif;
		///<summary>
		///rowControls control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableRow rowControls;
		///<summary>
		///btnBack control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		private global::System.Web.UI.WebControls.Button withEventsField_btnBack;
		protected global::System.Web.UI.WebControls.Button btnBack {
			get { return withEventsField_btnBack; }
			set {
				if (withEventsField_btnBack != null) {
					withEventsField_btnBack.Click -= btnBack_Click;
				}
				withEventsField_btnBack = value;
				if (withEventsField_btnBack != null) {
					withEventsField_btnBack.Click += btnBack_Click;
				}
			}
		}
	}
}
