using DotNetNuke;
using DotNetNuke.Common;
using DotNetNuke.Common.Utilities;
using DotNetNuke.Entities;
using DotNetNuke.Framework;
using DotNetNuke.Security;
using DotNetNuke.Services;
using DotNetNuke.Services.Exceptions;
using DotNetNuke.Services.Localization;
using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Collections.Specialized;
using System.Configuration;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Caching;
using System.Web.SessionState;
using System.Web.Security;
using System.Web.Profile;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------


namespace DotNetNuke.Modules.Gallery
{

	public partial class Maintenance
	{

		///<summary>
		///trNavigation control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableRow trNavigation;
		///<summary>
		///celHeaderLeft control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celHeaderLeft;
		///<summary>
		///celGalleryMenu control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celGalleryMenu;
		///<summary>
		///celBreadcrumbs control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celBreadcrumbs;
		///<summary>
		///celHeaderRight control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celHeaderRight;
		///<summary>
		///ClearCache1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		private global::System.Web.UI.WebControls.ImageButton withEventsField_ClearCache1;
		protected global::System.Web.UI.WebControls.ImageButton ClearCache1 {
			get { return withEventsField_ClearCache1; }
			set {
				if (withEventsField_ClearCache1 != null) {
					withEventsField_ClearCache1.Click -= ClearCache1_Click;
				}
				withEventsField_ClearCache1 = value;
				if (withEventsField_ClearCache1 != null) {
					withEventsField_ClearCache1.Click += ClearCache1_Click;
				}
			}

		}
		///<summary>
		///rowDetails control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableRow rowDetails;
		///<summary>
		///plPath control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plPath;
		///<summary>
		///txtPath control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtPath;
		///<summary>
		///plName control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plName;
		///<summary>
		///txtName control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtName;
		///<summary>
		///plAlbumInfo control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plAlbumInfo;
		///<summary>
		///lblAlbumInfo control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.Label lblAlbumInfo;
		///<summary>
		///btnSyncAll control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		private global::System.Web.UI.WebControls.LinkButton withEventsField_btnSyncAll;
		protected global::System.Web.UI.WebControls.LinkButton btnSyncAll {
			get { return withEventsField_btnSyncAll; }
			set {
				if (withEventsField_btnSyncAll != null) {
					withEventsField_btnSyncAll.Click -= btnSyncAll_Click;
				}
				withEventsField_btnSyncAll = value;
				if (withEventsField_btnSyncAll != null) {
					withEventsField_btnSyncAll.Click += btnSyncAll_Click;
				}
			}

		}
		///<summary>
		///btnDeleteAll control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		private global::System.Web.UI.WebControls.LinkButton withEventsField_btnDeleteAll;
		protected global::System.Web.UI.WebControls.LinkButton btnDeleteAll {
			get { return withEventsField_btnDeleteAll; }
			set {
				if (withEventsField_btnDeleteAll != null) {
					withEventsField_btnDeleteAll.Click -= btnDeleteAll_Click;
				}
				withEventsField_btnDeleteAll = value;
				if (withEventsField_btnDeleteAll != null) {
					withEventsField_btnDeleteAll.Click += btnDeleteAll_Click;
				}
			}

		}
		///<summary>
		///btnSelectAll control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.LinkButton btnSelectAll;
		///<summary>
		///btnDeselectAll control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.LinkButton btnDeselectAll;
		///<summary>
		///grdContent control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		private global::System.Web.UI.WebControls.DataGrid withEventsField_grdContent;
        protected global::System.Web.UI.WebControls.DataGrid grdContent;

		///<summary>
		///cmdReturn control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		private global::System.Web.UI.WebControls.LinkButton withEventsField_cmdReturn;
		protected global::System.Web.UI.WebControls.LinkButton cmdReturn {
			get { return withEventsField_cmdReturn; }
			set {
				if (withEventsField_cmdReturn != null) {
					withEventsField_cmdReturn.Click -= cmdReturn_Click;
				}
				withEventsField_cmdReturn = value;
				if (withEventsField_cmdReturn != null) {
					withEventsField_cmdReturn.Click += cmdReturn_Click;
				}
			}
		}
	}
}
