'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Gallery

  Partial Public Class Settings

    '''<summary>
    '''celHeaderLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celHeaderLeft As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lblAdminTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdminTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rowAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowAdmin As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''celBodyLeft0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celBodyLeft0 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''dshAdminSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dshAdminSettings As Global.DotNetNuke.UI.UserControls.SectionHeadControl

    '''<summary>
    '''tblAdminSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblAdminSettings As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''plRootURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plRootURL As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''lblHomeDirectory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHomeDirectory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RootURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RootURL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valRootURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valRootURL As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''plCreatedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plCreatedDate As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtCreatedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreatedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''plQuota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plQuota As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtQuota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuota As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Regularexpressionvalidator9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Regularexpressionvalidator9 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''plMaxFileSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plMaxFileSize As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtMaxFileSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaxFileSize As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Regularexpressionvalidator8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Regularexpressionvalidator8 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblMaxFileSizeWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxFileSizeWarning As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''plMaxPendingUploadsSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plMaxPendingUploadsSize As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtMaxPendingUploadsSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaxPendingUploadsSize As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Regularexpressionvalidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Regularexpressionvalidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''RangeValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator1 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''plAutoApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plAutoApproval As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkAutoApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAutoApproval As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plBuildCacheOnStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plBuildCacheOnStart As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkBuildCacheOnStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBuildCacheOnStart As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''celBodyRight0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celBodyRight0 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowDisplaySettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowDisplaySettings As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''celBodyLeft2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celBodyLeft2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''dshDisplaySettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dshDisplaySettings As Global.DotNetNuke.UI.UserControls.SectionHeadControl

    '''<summary>
    '''tblDisplaySettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblDisplaySettings As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''plSkin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plSkin As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlSkins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSkins As Global.DotNetNuke.Modules.Gallery.Views.TemplateList

    '''<summary>
    '''plGalleryTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plGalleryTitle As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtGalleryTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGalleryTitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''plDefaultAlbum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plDefaultAlbum As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlDefaultAlbum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDefaultAlbum As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''plImageExtensions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plImageExtensions As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''lblImageExtensions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImageExtensions As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''plMediaExtensions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plMediaExtensions As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''lblMediaExtensions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMediaExtensions As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDescription As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''plDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plDescription As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''plFixedWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plFixedWidth As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtFixedWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFixedWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valFixedWidth1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valFixedWidth1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valFixedWidth2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valFixedWidth2 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''plFixedHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plFixedHeight As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtFixedHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFixedHeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valFixedHeight1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valFixedHeight1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valFixedHeight2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valFixedHeight2 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''plStripWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plStripWidth As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtStripWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStripWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valStripWidth1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valStripWidth1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valStripWidth2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valStripWidth2 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''plStripHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plStripHeight As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtStripHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStripHeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valStripHeight1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valStripHeight1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valStripHeight2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valStripHeight2 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''plMaxThumbWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plMaxThumbWidth As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtMaxThumbWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaxThumbWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valMaxThumbWidth1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valMaxThumbWidth1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valMaxThumbWidth2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valMaxThumbWidth2 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''plMaxThumbHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plMaxThumbHeight As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtMaxThumbHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaxThumbHeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valMaxThumbHeight1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valMaxThumbHeight1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valMaxThumbHeight2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valMaxThumbHeight2 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''plEncoderQuality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plEncoderQuality As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtEncoderQuality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEncoderQuality As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valEncoderQuality1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valEncoderQuality1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valEncoderQuality2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valEncoderQuality2 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''plDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plDisplay As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''lstDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstDisplay As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''plCategoryValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plCategoryValues As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtCategoryValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCategoryValues As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''plSortProperties control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plSortProperties As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''lstSortProperties control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstSortProperties As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''plGallerySort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plGallerySort As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlGallerySort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGallerySort As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkDESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDESC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plGalleryView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plGalleryView As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlGalleryView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGalleryView As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkChangeView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkChangeView As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''celBodyRight2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celBodyRight2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''dshFeatureSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dshFeatureSettings As Global.DotNetNuke.UI.UserControls.SectionHeadControl

    '''<summary>
    '''tblFeatureSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFeatureSettings As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''plSlideshowSpeed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plSlideshowSpeed As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtSlideshowSpeed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSlideshowSpeed As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valSlideShowSpeed1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valSlideShowSpeed1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valSlideShowSpeed2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valSlideShowSpeed2 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''plSlideshow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plSlideshow As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkSlideshow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSlideshow As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plPopup As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPopup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plMultiLevelMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plMultiLevelMenu As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkMultiLevelMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMultiLevelMenu As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plWatermark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plWatermark As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkWatermark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWatermark As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plExif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plExif As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkExif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExif As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plVoting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plVoting As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkVoting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVoting As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plDownload As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDownload As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rowDownloadRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowDownloadRoles As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''plDownloadRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plDownloadRoles As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ctlDownloadRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDownloadRoles As Global.DotNetNuke.Modules.Gallery.WebControls.LookupControl

    '''<summary>
    '''dshPrivateGallery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dshPrivateGallery As Global.DotNetNuke.UI.UserControls.SectionHeadControl

    '''<summary>
    '''tblPrivateGallery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPrivateGallery As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''plPrivate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plPrivate As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkPrivate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPrivate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rowOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowOwner As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''plOwnerLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plOwnerLookup As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ctlOwnerLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlOwnerLookup As Global.DotNetNuke.Modules.Gallery.WebControls.LookupControl

    '''<summary>
    '''cmdSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cmdReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdReturn As Global.System.Web.UI.WebControls.LinkButton
  End Class
End Namespace
