using DotNetNuke;
using DotNetNuke.Common;
using DotNetNuke.Common.Utilities;
using DotNetNuke.Entities;
using DotNetNuke.Framework;
using DotNetNuke.Security;
using DotNetNuke.Services;
using DotNetNuke.Services.Exceptions;
using DotNetNuke.Services.Localization;
using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Collections.Specialized;
using System.Configuration;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Caching;
using System.Web.SessionState;
using System.Web.Security;
using System.Web.Profile;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------


namespace DotNetNuke.Modules.Gallery
{

	public partial class Settings
	{

		///<summary>
		///celHeaderLeft control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celHeaderLeft;
		///<summary>
		///lblAdminTitle control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.Label lblAdminTitle;
		///<summary>
		///rowAdmin control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableRow rowAdmin;
		///<summary>
		///celBodyLeft0 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celBodyLeft0;
		///<summary>
		///dshAdminSettings control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.SectionHeadControl dshAdminSettings;
		///<summary>
		///tblAdminSettings control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTable tblAdminSettings;
		///<summary>
		///plRootURL control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plRootURL;
		///<summary>
		///lblHomeDirectory control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.Label lblHomeDirectory;
		///<summary>
		///RootURL control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox RootURL;
		///<summary>
		///valRootURL control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RegularExpressionValidator valRootURL;
		///<summary>
		///plCreatedDate control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plCreatedDate;
		///<summary>
		///txtCreatedDate control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtCreatedDate;
		///<summary>
		///plQuota control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plQuota;
		///<summary>
		///txtQuota control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtQuota;
		///<summary>
		///Regularexpressionvalidator9 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RegularExpressionValidator Regularexpressionvalidator9;
		///<summary>
		///plMaxFileSize control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plMaxFileSize;
		///<summary>
		///txtMaxFileSize control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtMaxFileSize;
		///<summary>
		///Regularexpressionvalidator8 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RegularExpressionValidator Regularexpressionvalidator8;
		///<summary>
		///lblMaxFileSizeWarning control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.Label lblMaxFileSizeWarning;
		///<summary>
		///plMaxPendingUploadsSize control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plMaxPendingUploadsSize;
		///<summary>
		///txtMaxPendingUploadsSize control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtMaxPendingUploadsSize;
		///<summary>
		///Regularexpressionvalidator1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RegularExpressionValidator Regularexpressionvalidator1;
		///<summary>
		///RangeValidator1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RangeValidator RangeValidator1;
		///<summary>
		///plAutoApproval control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plAutoApproval;
		///<summary>
		///chkAutoApproval control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.CheckBox chkAutoApproval;
		///<summary>
		///plBuildCacheOnStart control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plBuildCacheOnStart;
		///<summary>
		///chkBuildCacheOnStart control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.CheckBox chkBuildCacheOnStart;
		///<summary>
		///celBodyRight0 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celBodyRight0;
		///<summary>
		///rowDisplaySettings control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableRow rowDisplaySettings;
		///<summary>
		///celBodyLeft2 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celBodyLeft2;
		///<summary>
		///dshDisplaySettings control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.SectionHeadControl dshDisplaySettings;
		///<summary>
		///tblDisplaySettings control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTable tblDisplaySettings;
		///<summary>
		///plSkin control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plSkin;
		///<summary>
		///ddlSkins control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.Modules.Gallery.Views.TemplateList ddlSkins;
		///<summary>
		///plGalleryTitle control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plGalleryTitle;
		///<summary>
		///txtGalleryTitle control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtGalleryTitle;
		///<summary>
		///plDefaultAlbum control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plDefaultAlbum;
		///<summary>
		///ddlDefaultAlbum control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.DropDownList ddlDefaultAlbum;
		///<summary>
		///plImageExtensions control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plImageExtensions;
		///<summary>
		///lblImageExtensions control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.Label lblImageExtensions;
		///<summary>
		///plMediaExtensions control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plMediaExtensions;
		///<summary>
		///lblMediaExtensions control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.Label lblMediaExtensions;
		///<summary>
		///trDescription control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableRow trDescription;
		///<summary>
		///plDescription control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plDescription;
		///<summary>
		///txtDescription control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtDescription;
		///<summary>
		///plFixedWidth control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plFixedWidth;
		///<summary>
		///txtFixedWidth control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtFixedWidth;
		///<summary>
		///valFixedWidth1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RequiredFieldValidator valFixedWidth1;
		///<summary>
		///valFixedWidth2 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RangeValidator valFixedWidth2;
		///<summary>
		///plFixedHeight control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plFixedHeight;
		///<summary>
		///txtFixedHeight control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtFixedHeight;
		///<summary>
		///valFixedHeight1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RequiredFieldValidator valFixedHeight1;
		///<summary>
		///valFixedHeight2 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RangeValidator valFixedHeight2;
		///<summary>
		///plStripWidth control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plStripWidth;
		///<summary>
		///txtStripWidth control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtStripWidth;
		///<summary>
		///valStripWidth1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RequiredFieldValidator valStripWidth1;
		///<summary>
		///valStripWidth2 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RangeValidator valStripWidth2;
		///<summary>
		///plStripHeight control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plStripHeight;
		///<summary>
		///txtStripHeight control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtStripHeight;
		///<summary>
		///valStripHeight1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RequiredFieldValidator valStripHeight1;
		///<summary>
		///valStripHeight2 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RangeValidator valStripHeight2;
		///<summary>
		///plMaxThumbWidth control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plMaxThumbWidth;
		///<summary>
		///txtMaxThumbWidth control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtMaxThumbWidth;
		///<summary>
		///valMaxThumbWidth1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RequiredFieldValidator valMaxThumbWidth1;
		///<summary>
		///valMaxThumbWidth2 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RangeValidator valMaxThumbWidth2;
		///<summary>
		///plMaxThumbHeight control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plMaxThumbHeight;
		///<summary>
		///txtMaxThumbHeight control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtMaxThumbHeight;
		///<summary>
		///valMaxThumbHeight1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RequiredFieldValidator valMaxThumbHeight1;
		///<summary>
		///valMaxThumbHeight2 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RangeValidator valMaxThumbHeight2;
		///<summary>
		///plEncoderQuality control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plEncoderQuality;
		///<summary>
		///txtEncoderQuality control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtEncoderQuality;
		///<summary>
		///valEncoderQuality1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RequiredFieldValidator valEncoderQuality1;
		///<summary>
		///valEncoderQuality2 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RangeValidator valEncoderQuality2;
		///<summary>
		///plDisplay control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plDisplay;
		///<summary>
		///lstDisplay control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.CheckBoxList lstDisplay;
		///<summary>
		///plCategoryValues control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plCategoryValues;
		///<summary>
		///txtCategoryValues control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtCategoryValues;
		///<summary>
		///plSortProperties control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plSortProperties;
		///<summary>
		///lstSortProperties control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.CheckBoxList lstSortProperties;
		///<summary>
		///plGallerySort control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plGallerySort;
		///<summary>
		///ddlGallerySort control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.DropDownList ddlGallerySort;
		///<summary>
		///chkDESC control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.CheckBox chkDESC;
		///<summary>
		///plGalleryView control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plGalleryView;
		///<summary>
		///ddlGalleryView control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.DropDownList ddlGalleryView;
		///<summary>
		///chkChangeView control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.CheckBox chkChangeView;
		///<summary>
		///celBodyRight2 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableCell celBodyRight2;
		///<summary>
		///dshFeatureSettings control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.SectionHeadControl dshFeatureSettings;
		///<summary>
		///tblFeatureSettings control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTable tblFeatureSettings;
		///<summary>
		///plSlideshowSpeed control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plSlideshowSpeed;
		///<summary>
		///txtSlideshowSpeed control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox txtSlideshowSpeed;
		///<summary>
		///valSlideShowSpeed1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RequiredFieldValidator valSlideShowSpeed1;
		///<summary>
		///valSlideShowSpeed2 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RangeValidator valSlideShowSpeed2;
		///<summary>
		///plSlideshow control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plSlideshow;
		///<summary>
		///chkSlideshow control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.CheckBox chkSlideshow;
		///<summary>
		///plPopup control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plPopup;
		///<summary>
		///chkPopup control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.CheckBox chkPopup;
		///<summary>
		///plMultiLevelMenu control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plMultiLevelMenu;
		///<summary>
		///chkMultiLevelMenu control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.CheckBox chkMultiLevelMenu;
		///<summary>
		///plWatermark control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plWatermark;
		///<summary>
		///chkWatermark control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.CheckBox chkWatermark;
		///<summary>
		///plExif control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plExif;
		///<summary>
		///chkExif control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.CheckBox chkExif;
		///<summary>
		///plVoting control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plVoting;
		///<summary>
		///chkVoting control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.CheckBox chkVoting;
		///<summary>
		///plDownload control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plDownload;
		///<summary>
		///chkDownload control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.CheckBox chkDownload;
		///<summary>
		///rowDownloadRoles control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableRow rowDownloadRoles;
		///<summary>
		///plDownloadRoles control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plDownloadRoles;
		///<summary>
		///ctlDownloadRoles control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.Modules.Gallery.WebControls.LookupControl ctlDownloadRoles;
		///<summary>
		///dshPrivateGallery control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.SectionHeadControl dshPrivateGallery;
		///<summary>
		///tblPrivateGallery control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTable tblPrivateGallery;
		///<summary>
		///plPrivate control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plPrivate;
		///<summary>
		///chkPrivate control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.CheckBox chkPrivate;
		///<summary>
		///rowOwner control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.HtmlControls.HtmlTableRow rowOwner;
		///<summary>
		///plOwnerLookup control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.UI.UserControls.LabelControl plOwnerLookup;
		///<summary>
		///ctlOwnerLookup control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::DotNetNuke.Modules.Gallery.WebControls.LookupControl ctlOwnerLookup;
		///<summary>
		///cmdSave control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		private global::System.Web.UI.WebControls.LinkButton withEventsField_cmdSave;
		protected global::System.Web.UI.WebControls.LinkButton cmdSave {
			get { return withEventsField_cmdSave; }
			set {
				if (withEventsField_cmdSave != null) {
					withEventsField_cmdSave.Click -= cmdSave_Click;
				}
				withEventsField_cmdSave = value;
				if (withEventsField_cmdSave != null) {
					withEventsField_cmdSave.Click += cmdSave_Click;
				}
			}

		}
		///<summary>
		///cmdReturn control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		private global::System.Web.UI.WebControls.LinkButton withEventsField_cmdReturn;
		protected global::System.Web.UI.WebControls.LinkButton cmdReturn {
			get { return withEventsField_cmdReturn; }
			set {
				if (withEventsField_cmdReturn != null) {
					withEventsField_cmdReturn.Click -= cmdReturn_Click;
				}
				withEventsField_cmdReturn = value;
				if (withEventsField_cmdReturn != null) {
					withEventsField_cmdReturn.Click += cmdReturn_Click;
				}
			}
		}
		public Settings()
		{
			PreRender += Page_PreRender;
			Load += Page_Load;
			Init += Page_Init;
		}
	}
}
