'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Gallery.WebControls

  Partial Public Class Viewer

    '''<summary>
    '''MovePrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MovePrevious As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''MoveNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MoveNext As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''ZoomOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ZoomOut As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''ZoomIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ZoomIn As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''RotateLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RotateLeft As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''RotateRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RotateRight As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''FlipX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlipX As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''FlipY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlipY As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''BWMinus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BWMinus As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Color control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Color As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''BWPlus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BWPlus As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''UpdateButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateButton As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''litInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litInfo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litDescription As Global.System.Web.UI.WebControls.Literal
  End Class
End Namespace
